Repository hmcts/hwf-publicapp, pull requests merged in 2023-12, with the labels that each got.

#725 RST-6087 email trim space
  app/models/forms/contact.rb
  app/models/forms/legal_representative_detail.rb
  spec/models/forms/contact_spec.rb
  spec/models/forms/legal_representative_detail_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-725

#729 RST-6083 changed link on checklist page
  app/views/home/checklist/_post_ucd.html.slim
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-729

#728 RST-6029 fixed translations on partner dob and name page
  config/locales/cy.yml
  config/locales/en.yml
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-728

#726 RST-6104 - Fixing summary page bug
  app/views/summaries/show.html.slim
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-726

#733 RST-6114 Sanitising age bands
  app/models/forms/dependent.rb
  spec/models/forms/dependent_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-733

#736 RST-6024 changes content for en and cy privacy policy
  config/locales/cy.yml
  config/locales/en.yml
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-736

#738 RST-6108 remove presence validation from legal_lit_friend email
  app/models/forms/legal_representative_detail.rb
  spec/models/forms/legal_representative_detail_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-738

#739 RST-6141 Clear income period
  app/services/clear_downstream_questions.rb
  spec/services/clear_downstream_questions_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-739

#740 Minor gem updates
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-740
