Repository hmcts/hwf-publicapp, pull requests merged in 2023-11, with the labels that each got.

#690 Revert "RST-5637-v2 UCD Content Change"
  config/locales/cy.yml
  config/locales/en.yml
  features/support/page_objects/confirmation_page.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-690

#691 Minor gem updates
  Gemfile.lock
  config/locales/cy.yml
  config/locales/en.yml
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-691

#693 RST-5897 personal details
  .env.test
  .rubocop.yml
  README.md
  app/helpers/application_helper.rb
  app/models/concerns/partner_dob_validatable.rb
  app/models/forms/base.rb
  app/models/forms/dob.rb
  app/models/forms/personal_detail.rb
  app/models/online_application.rb
  app/models/views/income_kinds.rb
  app/services/question_form_factory.rb
  app/services/storage.rb
  app/views/questions/forms/_dob.html.slim
  app/views/questions/forms/_personal_detail.html.slim
  app/views/summaries/show.html.slim
  config/locales/en.yml
  spec/models/forms/base_spec.rb
  spec/models/forms/dob_spec.rb
  spec/models/forms/fee_spec.rb
  spec/models/forms/personal_detail_spec.rb
  spec/models/views/income_kinds_spec.rb
  spec/services/online_application_builder_spec.rb
  spec/services/storage_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-693

#697 RST-5632 legal representative
  .rubocop.yml
  app/controllers/questions_controller.rb
  app/helpers/application_helper.rb
  app/helpers/title_helper.rb
  app/lib/feature_switch.rb
  app/models/concerns/partner_dob_validatable.rb
  app/models/forms/applying_on_behalf.rb
  app/models/forms/dob.rb
  app/models/forms/legal_representative.rb
  app/models/forms/legal_representative_detail.rb
  app/models/forms/over_16.rb
  app/models/online_application.rb
  app/services/clear_downstream_questions.rb
  app/services/navigation.rb
  app/services/navigation_helper.rb
  app/services/online_application_builder.rb
  app/views/questions/forms/_applying_on_behalf.html.slim
  app/views/questions/forms/_dob.html.slim
  app/views/questions/forms/_legal_representative.html.slim
  app/views/questions/forms/_legal_representative_detail.html.slim
  app/views/questions/forms/_over16.html.slim
  app/views/questions/headers/_applying_on_behalf.html.slim
  app/views/questions/headers/_legal_representative.html.slim
  app/views/questions/headers/_legal_representative_detail.html.slim
  app/views/questions/headers/_over16.html.slim
  app/views/summaries/_represented_by.html.slim
  app/views/summaries/show.html.slim
  config/environments/development.rb
  config/locales/en.yml
  config/settings.yml
  features/post_ucd_changes_flow.feature
  features/step_definitions/post_ucd_steps.rb
  features/support/generic_helpers.rb
  features/support/page_objects/legal_representative_detail_page.rb
  features/support/page_objects/legal_representative_page.rb
  features/support/page_objects/on_behalf_page.rb
  features/support/page_objects/over_16_page.rb
  spec/models/forms/dob_spec.rb
  spec/services/clear_downstream_questions_spec.rb
  spec/services/navigation_spec.rb
  spec/services/online_application_builder_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-697

#700 RST-5972 dependents
  app/helpers/children_helper.rb
  app/models/forms/dependent.rb
  app/models/online_application.rb
  app/models/views/summary.rb
  app/views/questions/forms/_dependent.html.slim
  app/views/questions/forms/dependents/_post_ucd.html.slim
  app/views/questions/forms/dependents/_pre_ucd.html.slim
  app/views/summaries/_children.html.slim
  app/views/summaries/show.html.slim
  config/locales/cy.yml
  config/locales/en.yml
  features/support/page_objects/dependent_page.rb
  spec/features/pages/benefits_question_spec.rb
  spec/models/forms/dependent_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-700

#702 Bufix -partner data reset
  app/lib/clear_partner_related_data.rb
  app/models/forms/dob.rb
  app/services/clear_downstream_questions.rb
  spec/lib/clear_partner_related_data_spec.rb
  spec/models/forms/dob_spec.rb
  spec/services/clear_downstream_questions_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-702

#701 RST-5984 Changed income_kind content
  app/helpers/income_helper.rb
  app/helpers/title_helper.rb
  app/helpers/yaml_helper.rb
  app/models/forms/income_kind.rb
  app/models/views/income_kinds.rb
  app/views/questions/forms/_income_kind.html.slim
  app/views/questions/forms/income_kind/_post_ucd.html.slim
  app/views/questions/forms/income_kind/_pre_ucd.html.slim
  app/views/questions/headers/_income_amount.html.slim
  app/views/questions/headers/_income_kind.html.slim
  app/views/questions/headers/_income_range.html.slim
  config/locales/cy.yml
  config/locales/en.yml
  features/income_kind.feature
  features/income_kind_ucd.feature
  features/step_definitions/income_kind_steps.rb
  features/support/generic_helpers.rb
  features/support/navigation_helper.rb
  features/support/page_objects/applying_on_behalf_page.rb
  features/support/page_objects/dependent_page.rb
  features/support/page_objects/income_kind_page.rb
  spec/features/pages/dependent_question_spec.rb
  spec/features/pages/income_question_spec.rb
  spec/models/forms/income_kind_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-701

#704 RST-5992 declaration of truth
  app/controllers/submissions_controller.rb
  app/controllers/summaries_controller.rb
  app/models/forms/statement.rb
  app/models/online_application.rb
  app/models/views/summary.rb
  app/views/summaries/_declaration.html.slim
  app/views/summaries/show.html.slim
  config/locales/cy.yml
  config/locales/en.yml
  spec/models/views/summary_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-704

#703 RST-6001 Confirmaion page content UCD
  app/views/confirmations/_online.html.slim
  app/views/confirmations/_paper.html.slim
  app/views/confirmations/online/_post_ucd.html.slim
  app/views/confirmations/online/_pre_ucd.html.slim
  app/views/confirmations/paper/_post_ucd.html.slim
  app/views/confirmations/paper/_pre_ucd.html.slim
  app/views/confirmations/refund.html.slim
  app/views/confirmations/refund/_post_ucd.html.slim
  app/views/confirmations/refund/_pre_ucd.html.slim
  config/locales/cy.yml
  config/locales/en.yml
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-703

#699 RST-5967 Changed What you need page content
  app/views/home/checklist.html.slim
  app/views/home/checklist/_post_ucd.html.slim
  app/views/home/checklist/_pre_ucd.html.slim
  config/locales/cy.yml
  config/locales/en.yml
  features/support/page_objects/checklist_page.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-699

#705 RST-5986 income period
  app/helpers/title_helper.rb
  app/models/forms/income_period.rb
  app/models/online_application.rb
  app/models/views/summary.rb
  app/views/questions/forms/_income_period.html.slim
  app/views/questions/headers/_income_period.html.slim
  app/views/summaries/_income.html.slim
  app/views/summaries/show.html.slim
  config/locales/cy.yml
  config/locales/en.yml
  config/settings.yml
  features/income_kind_ucd.feature
  features/step_definitions/income_range_steps.rb
  features/support/generic_helpers.rb
  features/support/page_objects/income_period_page.rb
  spec/services/online_application_builder_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-705

#696 RST-5956
  app/helpers/title_helper.rb
  app/views/questions/forms/_marital_status.html.slim
  app/views/questions/forms/_savings_and_investment.html.slim
  app/views/questions/forms/marital_status/_post_ucd.html.slim
  app/views/questions/forms/marital_status/_pre_ucd.html.slim
  app/views/questions/forms/savings_and_investment/_post_ucd.html.slim
  app/views/questions/forms/savings_and_investment/_pre_ucd.html.slim
  app/views/questions/forms/savings_and_investment/_savings_and_investment_conflicting.html.slim
  app/views/questions/forms/savings_and_investment/_savings_and_investment_joint_savings.html.slim
  app/views/questions/headers/_marital_status.html.slim
  app/views/questions/headers/_savings_and_investment.html.slim
  app/views/questions/headers/marital_status/_post_ucd.html.slim
  app/views/questions/headers/marital_status/_pre_ucd.html.slim
  app/views/questions/headers/savings_and_investment/_post_ucd.html.slim
  app/views/questions/headers/savings_and_investment/_pre_ucd.html.slim
  app/views/questions/headers/savings_and_investment/_subheader.html.slim
  config/locales/cy.yml
  config/locales/en.yml
  features/step_definitions/marital_status_steps.rb
  features/step_definitions/savings_and_investment_extra_steps.rb
  features/step_definitions/savings_and_investment_steps.rb
  features/support/navigation_helper.rb
  features/support/page_objects/marital_status_page.rb
  features/support/page_objects/savings_investment_extra_page.rb
  features/support/page_objects/savings_investment_page.rb
  features/ucd_marital_status.feature
  features/ucd_savings_investment.feature
  features/ucd_savings_investment_extra.feature
  spec/features/pages/national_insurance_question_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-696

#706 RST-5971 NI partner
  app/models/forms/partner_national_insurance.rb
  app/models/online_application.rb
  app/services/navigation_helper.rb
  app/services/navigation_ni_helper.rb
  app/views/questions/forms/_partner_national_insurance.html.slim
  app/views/questions/headers/_partner_national_insurance.html.slim
  app/views/summaries/show.html.slim
  config/locales/cy.yml
  config/locales/en.yml
  config/settings.yml
  features/step_definitions/income_kind_steps.rb
  features/support/generic_helpers.rb
  features/support/navigation_helper.rb
  features/support/page_objects/partner_national_insurance_page.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-706

#707 RST-6067 income page list
  app/views/questions/headers/_income_period.html.slim
  config/locales/cy.yml
  config/locales/en.yml
  features/step_definitions/savings_and_investment_steps.rb
  features/support/page_objects/summary_page.rb
  spec/support/feature_steps.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-707

#716 Fixing issue with clearing forms
  app/controllers/confirmations_controller.rb
  app/controllers/submissions_controller.rb
  app/services/storage.rb
  spec/controllers/confirmations_controller_spec.rb
  spec/controllers/submissions_controller_spec.rb
  spec/services/storage_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-716

#718 fixed logic to send last few income types
  app/models/forms/income_kind.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-718

#723 RST-6024 changes content for en and cy privacy policy
  config/locales/cy.yml
  config/locales/en.yml
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-723

#719 RST-6069 address lookup fix
  app/services/address_lookup.rb
  app/views/questions/headers/_applying_on_behalf.html.slim
  config/locales/cy.yml
  config/locales/en.yml
  spec/services/address_lookup_spec.rb
  spec/support/feature_steps.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-719

#720 Minor gem updates
  Gemfile
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-720

#724 RST-5993 banner
  app/assets/stylesheets/local/banners.scss
  app/views/questions/edit.html.slim
  app/views/questions/headers/_banner.html.slim
  config/locales/cy.yml
  config/locales/en.yml
  features/support/page_objects/base_page.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-724
