Repository hmcts/hwf-publicapp, pull requests merged in 2024-07, with the labels that each got.

#880 Minor gem updates
  Gemfile
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-880

#827 RST-5649 - Fix income amount validation (pre-UCD)
  app/models/forms/income_amount.rb
  features/home.feature
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-827

#885 Minor gem updates
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-885

#887 Rst-6743 add validation and refactor over_61 to 66
  app/models/forms/dob.rb
  app/models/forms/savings_and_investment_extra.rb
  app/models/online_application.rb
  app/models/views/summary.rb
  app/views/home/index.html.slim
  app/views/questions/forms/_dob.html.slim
  app/views/questions/forms/savings_and_investment_extra/_post_ucd.html.slim
  app/views/questions/forms/savings_and_investment_extra/_pre_ucd.html.slim
  charts/help-with-fees-publicapp/Chart.yaml
  config/locales/cy.yml
  config/locales/en.yml
  features/e2e.feature
  features/savings_investment_extra.feature
  features/support/page_objects/dob_page.rb
  spec/features/pages/savings_investment_extra_question_spec.rb
  spec/models/forms/dob_spec.rb
  spec/models/forms/savings_and_investment_extra_spec.rb
  spec/models/views/summary_spec.rb
  spec/services/online_application_builder_spec.rb
  spec/support/feature_steps.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-887

#892 RST-6787 - update rexml to 3.3.2
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-892

#873 RST-6614
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/modules/partner-national-insurance.js
  app/helpers/application_helper.rb
  app/lib/clear_partner_related_data.rb
  app/models/forms/partner_national_insurance.rb
  app/models/online_application.rb
  app/views/questions/forms/_partner_national_insurance.html.slim
  app/views/summaries/show.html.slim
  config/locales/cy.yml
  config/locales/en.yml
  features/post_ucd_changes_flow.feature
  features/support/page_objects/partner_national_insurance_page.rb
  sonar-project.properties
  spec/models/forms/partner_national_insurance_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-873

#895 RST-6780 add missing welsh translations
  charts/help-with-fees-publicapp/Chart.yaml
  config/locales/cy.yml
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-895

#893 RST-6762 Text update for wages income kind
  config/locales/cy.yml
  config/locales/en.yml
  features/income_kind.feature
  features/income_kind_ucd.feature
  spec/models/forms/income_kind_spec.rb
  spec/models/views/income_kinds_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-893
