Repository hmcts/hwf-publicapp, pull requests merged in 2024-04, with the labels that each got.

#818 Minor gem updates
  .rubocop.yml
  Gemfile.lock
  charts/help-with-fees-publicapp/Chart.yaml
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-818

#813 RST-6438 no income post ucd will lead to income period page
  app/services/navigation_helper.rb
  charts/help-with-fees-publicapp/Chart.yaml
  features/income_kind_ucd.feature
  features/step_definitions/income_period_steps.rb
  features/step_definitions/income_range_steps.rb
  features/support/page_objects/income_period_page.rb
  spec/services/navigation_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-813

#820 RST-6456 Validate over 16 vs over 61 on savings page
  .rubocop.yml
  app/models/forms/savings_and_investment_extra.rb
  app/views/questions/forms/savings_and_investment_extra/_post_ucd.html.slim
  config/locales/cy.yml
  config/locales/en.yml
  spec/models/forms/savings_and_investment_extra_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-820

#825 Updating minor gems and frontend lib
  .rubocop.yml
  Gemfile.lock
  app/views/layouts/application.html.slim
  app/views/layouts/moj_template.html.erb
  package-lock.json
  package.json
  public/400.html
  public/404.html
  public/500.html
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-825

#791 RST-5614 - change field to text to allow validations to work correctly
  README.md
  app/views/questions/forms/dependents/_pre_ucd.html.slim
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-791

#830 RST-6154 - Removing Zendesk reference
  .rubocop.yml
  charts/help-with-fees-publicapp/Chart.yaml
  charts/help-with-fees-publicapp/values.yaml
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-830

#828 Removing foreman from Gemfile
  Gemfile
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-828

#833 Minor gem updates v5
  Gemfile.lock
  package-lock.json
  package.json
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-833

#839 RST-6580 Minor ruby update
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  Jenkinsfile_CNP
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-839

#837 RST-6433 - update crown logo
  app/views/layouts/moj_template.html.erb
  public/400.html
  public/404.html
  public/500.html
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-837
