Repository hmcts/hwf-publicapp, pull requests merged in 2024-06, with the labels that each got.

#860 Minor ruby and gem updates
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  Jenkinsfile_CNP
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-860

#863 Minor gem updates
  Gemfile
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-863

#867 Minor gem updates
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  Jenkinsfile_CNP
  charts/help-with-fees-publicapp/Chart.yaml
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-867

#870 RST-6615 Update text for NI page
  config/locales/cy.yml
  config/locales/en.yml
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-870

#879 Test suite update: Post UCD flow
  features/post_ucd_changes_flow.feature
  features/step_definitions/dob_steps.rb
  features/step_definitions/national_insurance_steps.rb
  features/step_definitions/personal_details_steps.rb
  features/step_definitions/post_ucd_steps.rb
  features/support/page_objects/dob_page.rb
  features/support/page_objects/personal_details_page.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-879
