Repository hmcts/hwf-publicapp, pull requests merged in 2024-03, with the labels that each got.

#799 RST-6382 Updating govuk-frentend to 5.2
  app/assets/javascripts/application.js
  app/assets/stylesheets/application-ie8.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/ie7.scss
  app/assets/stylesheets/ie8.scss
  app/views/layouts/moj_template.html.erb
  config/initializers/assets.rb
  package-lock.json
  package.json
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-799

#802 RST-6344 Updating ruby to 3.3
  .ruby-version
  Dockerfile
  charts/help-with-fees-publicapp/Chart.yaml
  package-lock.json
  package.json
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-802

#805 RST-6419 Fixing over and under 16 validation
  app/models/forms/dob.rb
  config/locales/cy.yml
  config/locales/en.yml
  spec/models/forms/dob_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-805

#807 RST-6109 Adding position at firm field
  app/models/forms/legal_representative_detail.rb
  app/models/online_application.rb
  app/models/views/summary.rb
  app/views/questions/forms/_legal_representative_detail.html.slim
  app/views/summaries/_represented_by.html.slim
  config/locales/cy.yml
  config/locales/en.yml
  spec/models/forms/legal_representative_detail_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-807

#809 RST-6344 - Ruby 3.3 and gem updates
  Dockerfile
  Gemfile
  Gemfile.lock
  Jenkinsfile_CNP
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-809

#788 RST-5613 - fix validations when paid is false
  app/models/forms/fee.rb
  spec/models/forms/fee_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-788

#781 RST 6068 - update national insurance steps for post-UCD journey
  README.md
  app/models/forms/national_insurance.rb
  app/services/navigation_helper.rb
  app/services/navigation_ni_helper.rb
  app/views/questions/forms/_national_insurance.html.slim
  app/views/questions/forms/_national_insurance_presence.html.slim
  app/views/questions/forms/national_insurance/_post_ucd.html.slim
  app/views/questions/forms/national_insurance/_pre_ucd.html.slim
  app/views/questions/headers/_national_insurance.html.slim
  app/views/questions/headers/national_insurance/_post_ucd.html.slim
  app/views/questions/headers/national_insurance/_pre_ucd.html.slim
  charts/help-with-fees-publicapp/Chart.yaml
  charts/help-with-fees-publicapp/values.yaml
  config/locales/en.yml
  config/settings.yml
  features/post_ucd_changes_flow.feature
  features/support/navigation_helper.rb
  features/support/page_objects/fee_page.rb
  features/support/page_objects/marital_status_page.rb
  features/support/page_objects/national_insurance_page.rb
  features/support/page_objects/on_behalf_page.rb
  spec/features/pages/national_insurance_question_spec.rb
  spec/models/forms/national_insurance_spec.rb
  spec/services/navigation_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-781

#803 RST-6379 - Remove probation date validation
  app/models/forms/probate.rb
  features/probate.feature
  spec/features/pages/probate_question_spec.rb
  spec/models/forms/probate_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-803

#804 RST-6107 - Disable Contact page if legal representative selected
  app/services/navigation_helper.rb
  app/views/summaries/show.html.slim
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-804

#811 RST-6434 Error message fix
  config/locales/cy.yml
  config/locales/en.yml
  features/step_definitions/summary_steps.rb
  spec/models/forms/dob_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-811

#810 RST-6358- fix radio buttons when form page errors
  config/application.rb
  features/step_definitions/summary_steps.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-810

#814 RST-6483 - Fix next form step after national insurance
  app/services/navigation_ni_helper.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-814
