Repository hmcts/hwf-publicapp, pull requests merged in 2024-09, with the labels that each got.

#930 Ruby downgrade for CI fix
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  Jenkinsfile_CNP
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-930

#924 RST-6825 Content update for children living with you
  charts/help-with-fees-publicapp/Chart.yaml
  config/locales/cy.yml
  config/locales/en.yml
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-924

#922 Added validation to partner_dob so the user cannot enter zeros for th…
  app/models/concerns/partner_dob_validatable.rb
  spec/models/forms/dob_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-922

#939 Gem updates for security
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-939
