Repository hmcts/hwf-publicapp, pull requests merged in 2024-12, with the labels that each got.

#978 Minor gem updates
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-978

#964 RST-6885 - Feature tests tidy up - navigation helper
  Gemfile
  Gemfile.lock
  features/apply_on_behalf.feature
  features/e2e.feature
  features/form_name.feature
  features/income_kind/income_kind_married.feature
  features/income_kind/income_kind_single.feature
  features/post_ucd_changes_flow.feature
  features/step_definitions/address_steps.rb
  features/step_definitions/benefit_steps.rb
  features/step_definitions/claim_steps.rb
  features/step_definitions/confirmation_steps.rb
  features/step_definitions/contact_steps.rb
  features/step_definitions/dependent_steps.rb
  features/step_definitions/dob_steps.rb
  features/step_definitions/income_kind_steps.rb
  features/step_definitions/legal_representative_steps.rb
  features/step_definitions/national_insurance_steps.rb
  features/step_definitions/personal_details_steps.rb
  features/step_definitions/probate_steps.rb
  features/step_definitions/savings_and_investment_extra_steps.rb
  features/step_definitions/savings_and_investment_steps.rb
  features/step_definitions/summary_steps.rb
  features/support/apply_on_behalf.feature
  features/support/generic_helpers.rb
  features/support/navigation_helper.rb
  features/support/page_objects/on_behalf_page.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-964

#985 Minor gem updates
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-985
