Repository hmcts/hwf-publicapp, pull requests merged in 2025-02, with the labels that each got.

#1009 RST-6960a Check if cookie domain is valid
  charts/help-with-fees-publicapp/Chart.yaml
  config/initializers/session_store.rb
  config/settings.yml
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-1009

#1015 RST-7126 Removing app insight
  Gemfile
  Gemfile.lock
  config/application.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-1015

#1018 RST-7139 - Redirect change national insurance number to correct page
  app/models/forms/national_insurance.rb
  app/models/forms/national_insurance_presence.rb
  app/services/clear_downstream_questions.rb
  app/services/navigation_helper.rb
  app/services/navigation_ni_helper.rb
  app/views/questions/forms/_national_insurance_presence.html.slim
  app/views/questions/forms/national_insurance/_national_insurance.html.slim
  app/views/questions/headers/_national_insurance_presence.html.slim
  app/views/summaries/show.html.slim
  charts/help-with-fees-publicapp/Chart.yaml
  config/locales/cy.yml
  config/locales/en.yml
  features/step_definitions/national_insurance_presence_steps.rb
  features/step_definitions/national_insurance_steps.rb
  features/support/generic_helpers.rb
  features/support/page_objects/national_insurance_page.rb
  features/support/page_objects/national_insurance_presence_page.rb
  features/support/page_objects/summary_page.rb
  spec/features/pages/national_insurance_question_spec.rb
  spec/models/forms/national_insurance_presence_spec.rb
  spec/models/forms/national_insurance_spec.rb
  spec/services/navigation_spec.rb
  spec/support/feature_steps.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-1018

#1014 RST-7068 Children page select refactor
  app/assets/javascripts/application.js
  app/assets/javascripts/modules/select-children-show.js
  app/controllers/questions_controller.rb
  app/models/forms/dependent.rb
  app/views/questions/forms/dependents/_dependent.html.slim
  config/locales/cy.yml
  config/locales/en.yml
  features/dependent/dependent_married.feature
  features/dependent/dependent_single.feature
  features/e2e.feature
  features/step_definitions/dependent_steps.rb
  features/support/page_objects/dependent_page.rb
  spec/features/pages/dependent_question_spec.rb
  spec/models/forms/dependent_spec.rb
  spec/support/feature_steps.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-1014

#1017 RST-7091 - No partner details where no applicant NI
  app/helpers/title_helper.rb
  app/models/forms/dob.rb
  app/models/forms/personal_detail.rb
  app/services/navigation_ni_helper.rb
  app/views/questions/forms/_dob.html.slim
  app/views/questions/forms/_personal_detail.html.slim
  app/views/summaries/show.html.slim
  charts/help-with-fees-publicapp/Chart.yaml
  features/step_definitions/dob_steps.rb
  features/step_definitions/summary_steps.rb
  features/summary/summary_married.feature
  features/support/navigation_helper.rb
  features/support/page_objects/partner_national_insurance_page.rb
  features/support/page_objects/summary_page.rb
  spec/models/forms/dob_spec.rb
  spec/models/forms/personal_detail_spec.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-1017

#1022 Take user to yes radio instead of form when click error link
  app/views/questions/forms/national_insurance/_national_insurance.html.slim
  spec/features/pages/national_insurance_question_spec.rb
  spec/support/feature_steps.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-1022

#1026 Minor gem and ruby update
  .rubocop.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  Jenkinsfile_CNP
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-1026

#1035 RST 7142 Add new content to 'Important: read before you start' page.
  Gemfile.lock
  app/views/home/checklist/_checklist.html.slim
  config/locales/cy.yml
  config/locales/en.yml
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-1035

#1036 Minor gem update
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-1036

#1037 RST-7076 Back with the cookies config
  config/initializers/session_store.rb
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-1037
