Repository hmcts/hwf-publicapp, pull requests merged in 2025-09, with the labels that each got.

#1089 RST-7289 inital for propshaft refactor
  .gitignore
  Dockerfile
  Gemfile
  Gemfile.lock
  Jenkinsfile_CNP
  Procfile.dev
  README.md
  app/assets/builds/.keep
  app/assets/config/_manifest.js
  app/assets/stylesheets/_application.scss
  app/assets/stylesheets/application.sass.scss
  app/assets/stylesheets/confirmation-print.css
  app/assets/stylesheets/local/buttons.scss
  app/assets/stylesheets/local/colours.scss
  app/assets/stylesheets/local/icons.scss
  app/assets/stylesheets/local/links.scss
  app/assets/stylesheets/local/mixins.scss
  app/assets/stylesheets/local/panels.scss
  app/assets/stylesheets/local/typography.scss
  app/javascript/application.js
  app/javascript/modules/address-lookup.js
  app/javascript/modules/external-links.js
  app/javascript/modules/form-name.js
  app/javascript/modules/income-sources.js
  app/javascript/modules/module_loader.js
  app/javascript/modules/partner-national-insurance.js
  app/javascript/modules/print-page.js
  app/javascript/modules/restart-application.js
  app/javascript/modules/select-children-show.js
  app/javascript/modules/selection-buttons.js
  app/javascript/modules/show-hide.js
  app/javascript/modules/uppercase-fields.js
  app/views/confirmations/_stylesheets.html.slim
  app/views/layouts/application.html.slim
  app/views/layouts/moj_template.html.erb
  charts/help-with-fees-publicapp/Chart.yaml
  package-lock.json
  package.json
  sonar-project.properties
  webpack.config.js
  yarn.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-1089

#1146 Minor gem updates
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-1146

#1151 Minor gem updates
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-1151

#1154 Nightly dev
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  lib/tasks/fortify.rake
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-1154

#1161 RST-7601 date hint
  app/helpers/application_helper.rb
  app/views/questions/forms/_dob.html.slim
  app/views/questions/forms/_fee.html.slim
  app/views/questions/forms/_probate.html.slim
  config/locales/cy.yml
  config/locales/en.yml
  features/step_definitions/dob_steps.rb
  features/step_definitions/probate_steps.rb
  features/support/page_objects/dob_page.rb
  features/support/page_objects/probate_page.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm, rel:help-with-fees-publicapp-pr-1161
