Repository hmcts/hwf-publicapp, pull requests merged in 2025-01, with the labels that each got.

#994 Minor gem updates
  Gemfile.lock
Labels: ns:help-with-fees, prd:help-with-fees, rel:help-with-fees-publicapp-pr-994

#1001 RST-7071 - Ruby update
  .rubocop.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  Jenkinsfile_CNP
  package.json
Labels: ns:help-with-fees, prd:help-with-fees

#1000 RST-6960 Fix cookie rejection error
  charts/help-with-fees-publicapp/Chart.yaml
  config/initializers/session_store.rb
Labels: ns:help-with-fees, prd:help-with-fees, enable_keep_helm
